server:
  port: 8090

spring:
  application:
    name: wallet-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVICE_URL:http://localhost:8093}/.well-known/jwks.json

  flyway:
    url: ${SPRING_FLYWAY_URL}
    user: ${SPRING_FLYWAY_USER}
    password: ${SPRING_FLYWAY_PASSWORD}
    locations: classpath:db/migration

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
    pool:
      max-size: 20
      initial-size: 5
      max-idle-time: 30m
      max-acquire-time: 30s
  cloud:
    consul:
      discovery:
        prefer-ip-address: true
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: wallet-service

service:
  username: ${SERVICE_USERNAME:wallet-svc}
  password: ${SERVICE_PASSWORD:names}

payment:
  service:
    base-url: ${PAYMENT_SERVICE_URL:http://localhost:8092}

logging:
  level:
    com.ekenya.wallet: INFO
    org.springframework.transaction: DEBUG
