server:
  port: 8092

spring:
  application:
    name: payment-service

  flyway:
    url: ${SPRING_FLYWAY_URL}
    user: ${SPRING_FLYWAY_USER}
    password: ${SPRING_FLYWAY_PASSWORD}
    locations: classpath:db/migration

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVICE_URL:http://localhost:8093}/.well-known/jwks.json
  cloud:
    consul:
      discovery:
        hostname: ${CONSUL_HOST:localhost}
        port: 8500
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: payment-service
sms:
  username: ${SMS_USERNAME}
  password: ${SMS_PASSWORD}
  api-url: ${SMS_API_URL}
  client-id: ${SMS_CLIENT_ID}
  sender: ${SMS_SENDER}


tcp:
  base-url: ${TCP_BASE_URL}
  org: ${TCP_ORG}
  key: ${TCP_KEY}
  service-id: ${TCP_SERVICE_ID:1010}

intercape:
  base-url: ${INTERCAPE_BASE_URL:https://www.paybills.co.bw:8601/ecommerce/intercape}
  username: ${INTERCAPE_USERNAME}
  password: ${INTERCAPE_PASSWORD}
  client-id: ${INTERCAPE_CLIENT_ID}
  service-id: ${INTERCAPE_SERVICE_ID:1006}

billing:
  base-url: ${BILLING_BASE_URL}
  default-base-url: /v2/api/send
  username: ${BILLING_USERNAME}
  password: ${BILLING_PASSWORD}
  client-id: ${BILLING_CLIENT_ID}
  services:
    - service-code: BPC_TRANSACTION
      service-id: "1005"
      endpoint: /v2/api/vend
    - service-code: ACCESS_TOKEN
      endpoint: /api/access_token
    - service-code: BPC_PRESENTMENT
      endpoint: /api/Confirm_BPC_Customer
    - service-code: DSTV
      service-id: "1001"
    - service-code: AIRTIME_ORANGE
      service-id: "1004"
    - service-code: AIRTIME_BTC
      service-id: "1003"
    - service-code: AIRTIME_MASCOM
      service-id: "1002"
    - service-code: INTERCAPE
      service-id: "1006"
