server:
  port: 8092

spring:
  application:
    name: payment-service

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: payment-service

sms:
  username: ${SMS_USERNAME}
  password: ${SMS_PASSWORD}
  api-url: ${SMS_API_URL}
  client-id: ${SMS_CLIENT_ID}
  sender: ${SMS_SENDER}
