server:
  port: 8091

spring:
  application:
    name: wallet-user-management

  flyway:
    url: ${SPRING_FLYWAY_URL}
    user: ${SPRING_FLYWAY_USER}
    password: ${SPRING_FLYWAY_PASSWORD}
    schemas: users

    locations: classpath:db/migration
    create-schemas: true

  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
    pool:
      max-size: 10
      initial-size: 2

  codec:
    max-in-memory-size: 10MB

file:
  upload-dir: ${FILE_UPLOAD_DIR:./uploads}

services:
  wallet-service:
    url: ${WALLET_SERVICE_URL}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: wallet-user-management
